---
- name: Enable NTP config on IOS
  ios_ntp:
    logging: yes
    server: "{{ ntp_server }}"

- name: Set correct NTP interface
  ios_ntp:
    source_int: "{{ ntp_interface }}"
    vrf_name: "{{ ntp_vrf }}"