---
- name: Enable NTP config on NXOS
  nxos_ntp:
    server: "{{ ntp_server }}"
    source_int: "{{ ntp_interface }}"
    vrf_name: "{{ ntp_vrf }}"

- name: Enable NTP master on core Switches
  nxos_ntp_options:
    logging: yes
    master: yes
  when: "'core' in group_names"