- name: "Demonstrate connecting to switches"
  hosts: cisco_routers
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
    - name: Gather facts (ios)
      ios_facts:
      when: ansible_network_os == 'ios'

    ###
    # Demonstrate variables
    #
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Facts from a specific host
      debug:
        var: hostvars['router1']

    ###
    # Get running configuration
    #
    - name: Get Running Config
      when: ansible_network_os == 'ios'
      ios_command:
        commands: show run
      register: config
    
    - name: Print Running Config
      debug:
        var: config.stdout_lines
