---
- name: Create OSPF Instances on NXOS
  with_items: "{{ ospf_instances }}"
  nxos_ospf:
    ospf: "{{ item.ospf }}"

- name: Associate L3 Interfaces with OSPF on NXOS
  with_items: "{{ ospf_interfaces }}"
  nxos_interface_ospf:
    interface: "{{ item.interface }}"
    area: "{{ item.area | default(area) }}"
    ospf: "{{ item.ospf | default(ospf)) }}"
    network: "{{ item.ospf_network_type | default(network) }}"