---
- name: Admin Up and Description set
  with_items: "{{ access_ports }}"
  ios_config:
    src: access_ports.j2
  when: access_ports is defined

#- name: Debug Template Text
#  with_items: "{{ access_ports }}"
#  template:
#    src: access_ports.j2
#    dest: /tmp/testtemplate.txt 