---
- name: test
  debug:
    msg: "{{ lookup('vars',l3_interfaces.name) }}"

- name: Make L3 interfaces into routed ports on NXOS
  nxos_interface:
    aggregate: "{{ lookup('vars',l3_interfaces.name) }}"

- name: Create L3 Interfaces on NXOS
  nxos_l3_interface:
    aggregate: "{{ l3_interfaces }}"