---
#- name: Make L3 interfaces into routed ports on NXOS
#  with_items: "{{ l3_interfaces }}"
#  nxos_interface:
#    name: "{{ item.name }}"
#    admin_state: up
#    mode: layer3

- name: Make L3 interfaces into routed ports on NXOS
  nxos_interface:
    aggregate: "{{ l3_interfaces | subelements('name') | list }}"
    admin_state: up
    mode: layer3

- name: Create L3 Interfaces on NXOS
  nxos_l3_interface:
    aggregate: "{{ l3_interfaces }}"