---
- name: Enable and set description on trunk ports
  nxos_interface:
    aggregate: "{{ trunk_ports }}"
    mode: layer2

- name: Create trunk ports on NXOS
  nxos_l2_interface:
    aggregate: "{{ trunk_ports }}"
    mode: trunk