---
- name: Enable and set description on trunk ports
  with_items: "{{ trunk_ports }}"
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer2

- name: Create trunk ports on NXOS
  with_items: "{{ trunk_ports }}"
  nxos_l2_interface:
    name: "{{ item.interface }}"
    mode: trunk