---
ansible_host: 172.16.1.202
l3_interfaces:
  - name: Ethernet1/1
    ipv4: 10.0.1.101/31
ospf_interfaces:
  - interface: Ethernet1/1
    area: 0
    ospf: 1
    network: point-to-point
ospf_instances:
  - ospf: 1