---
ansible_host: 172.16.1.200
features:
  - interface-vlan
  - ospf
l3_interfaces:
  - name: Ethernet1/6
    ipv4: 10.0.0.2/31
  - name: Ethernet1/2
    ipv4: 10.0.1.98/31
  - name: Vlan4
    ipv4: 10.0.1.4/31
ospf_interfaces:
  - interface: Ethernet1/1
    area: 0
    ospf: 1
    ospf_network_type: point-to-point
  - interface: Ethernet1/2
    area: 0
    ospf: 1
    ospf_network_type: point-to-point
  - interface: Ethernet1/6
    area: 0
    ospf: 1
    ospf_network_type: point-to-point
  - interface: Vlan4
    area: 0
    ospf: 1
    ospf_network_type: point-to-point
ospf_instances:
  - ospf: 1
trunk_ports:
  - interface: Ethernet1/3
  - interface: Ethernet1/4
  - interface: Ethernet1/5
ntp_interface: Ethernet1/6
