---
ansible_host: 172.16.1.200
features:
  - interface-vlan
  - ospf
l3_interfaces:
  - name: Ethernet1/6
    ipv4: 10.0.0.2/31
  - name: Ethernet1/2
    ipv4: 10.0.1.98/31
  - name: Vlan4
    ipv4: 10.0.1.4/31
  - name: Vlan5
    ipv4: 10.0.5.1/24
  - name: Vlan6
    ipv4: 10.0.6.1/24
  - name: Vlan7
    ipv4: 10.0.7.1/24
  - name: Vlan8
    ipv4: 10.0.8.1/24
ospf_interfaces:
  - interface: Ethernet1/1
  - interface: Ethernet1/2
  - interface: Ethernet1/6
  - interface: Vlan4
  - interface: Vlan5
    ospf_network_type: broadcast
  - interface: Vlan6
    ospf_network_type: broadcast
  - interface: Vlan7
    ospf_network_type: broadcast
  - interface: Vlan8
    ospf_network_type: broadcast
ospf_instances:
  - ospf: 1
trunk_ports:
  - name: Ethernet1/3
  - name: Ethernet1/4
  - name: Ethernet1/5
ntp_interface: Ethernet1/6
