---
ansible_host: 172.16.1.220
features:
  - interface-vlan
  - ospf
l3_interfaces:
  - name: Ethernet1/1
    ipv4: 10.0.0.3/31
  - name: Vlan24
    ipv4: 10.0.21.4/31
  - name: Vlan25
    ipv4: 10.0.25.1/24
  - name: Vlan26
    ipv4: 10.0.26.1/24
  - name: Vlan27
    ipv4: 10.0.27.1/24
  - name: Vlan28
    ipv4: 10.0.28.1/24
ospf_interfaces:
  - interface: Ethernet1/1
  - interface: Vlan24
  - interface: Vlan25
    ospf_network_type: broadcast
  - interface: Vlan26
    ospf_network_type: broadcast
  - interface: Vlan27
    ospf_network_type: broadcast
  - interface: Vlan28
    ospf_network_type: broadcast
ospf_instances:
  - ospf: 1
trunk_ports:
  - name: Ethernet1/3
  - name: Ethernet1/4
  - name: Ethernet1/5
ntp_interface: Ethernet1/1