---
ansible_host: 172.16.1.201
features:
  - ospf
l3_interfaces:
  - name: Ethernet1/1
    ipv4: 10.0.1.99/31
  - name: Ethernet1/2
    ipv4: 10.0.1.100/31
  - name: Ethernet1/3
    ipv4: 10.0.1.102/31
ospf_interfaces:
  - interface: Ethernet1/1
    area: 0
    ospf: 1
  - interface: Ethernet1/2
    area: 0
    ospf: 1
  - interface: Ethernet1/3
    area: 0
    ospf: 1
ospf_instances:
  - ospf: 1